name: clock_in_it
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.0
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  bloc_test: ^9.1.3
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
